import 'package:flutter/material.dart';

enum AppLanguage {
  id, // Bahasa Indonesia
  en, // English
  su, // Basa Sunda
  jv, // Basa Jawa
}

class LanguageManager {
  LanguageManager._privateConstructor();
  static final LanguageManager instance = LanguageManager._privateConstructor();

  final ValueNotifier<AppLanguage> currentLanguageNotifier =
      ValueNotifier<AppLanguage>(AppLanguage.id);

  AppLanguage get currentLanguage => currentLanguageNotifier.value;

  String get currentLanguageCode {
    switch (currentLanguage) {
      case AppLanguage.id:
        return 'id';
      case AppLanguage.en:
        return 'en';
      case AppLanguage.su:
        return 'su';
      case AppLanguage.jv:
        return 'jv';
    }
  }

  String get currentLanguageDisplayName {
    switch (currentLanguage) {
      case AppLanguage.id:
        return 'Indonesia';
      case AppLanguage.en:
        return 'English';
      case AppLanguage.su:
        return 'Basa Sunda';
      case AppLanguage.jv:
        return 'Basa Jawa';
    }
  }

  void setLanguage(AppLanguage language) {
    currentLanguageNotifier.value = language;
  }

  // Kamus terjemahan untuk pengaturan & sub-halaman
  static final Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.id: {
      // Pengaturan Umum
      'settings_title': 'Pengaturan',
      'account': 'AKUN',
      'edit_profile': 'Edit Profil',
      'change_password': 'Ubah Kata Sandi',
      'preferences': 'PREFERENSI',
      'notifications': 'Notifikasi',
      'language': 'Bahasa',
      'help_and_info': 'BANTUAN & INFORMASI',
      'help_center': 'Pusat Bantuan',
      'about_app': 'Tentang Aplikasi',
      'logout': 'Keluar dari Akun',
      'logout_confirm_title': 'Konfirmasi Keluar',
      'logout_confirm_desc': 'Apakah Anda yakin ingin keluar dari akun admin ini?',
      'cancel': 'Batal',
      'save': 'Simpan Perubahan',
      'loading': 'Memuat...',
      'success': 'Berhasil',
      'error': 'Terjadi Kesalahan',
      // Edit Profil
      'profile_name': 'Nama Lengkap',
      'profile_nik': 'NIK / Nomor Karyawan',
      'profile_phone': 'Nomor Telepon / WhatsApp',
      'profile_email': 'Email Akun Admin (Tidak Dapat Diubah)',
      'profile_role': 'Peran Sistem',
      'profile_saved': 'Profil berhasil diperbarui!',
      // Kata Sandi
      'current_password': 'Kata Sandi Lama',
      'new_password': 'Kata Sandi Baru',
      'confirm_password': 'Konfirmasi Kata Sandi Baru',
      'password_min_length': 'Minimal 6 karakter',
      'password_match_error': 'Konfirmasi kata sandi tidak cocok',
      'password_success': 'Kata sandi berhasil diperbarui!',
      // Notifikasi
      'notif_title': 'Pengaturan Notifikasi',
      'notif_booking_title': 'Peminjaman Baru',
      'notif_booking_desc': 'Dapatkan pemberitahuan seketika saat ada karyawan mengajukan peminjaman.',
      'notif_geofence_title': 'Peringatan Geofence',
      'notif_geofence_desc': 'Peringatan darurat jika armada keluar dari area operasional yang ditentukan.',
      'notif_tracking_title': 'Live Tracking',
      'notif_tracking_desc': 'Update status pergerakan dan posisi kendaraan dinas.',
      'notif_sound_title': 'Suara & Getar',
      'notif_sound_desc': 'Bunyikan nada dering untuk notifikasi prioritas tinggi.',
      'notif_email_title': 'Ringkasan Laporan Mingguan',
      'notif_email_desc': 'Kirimkan rekapitulasi data peminjaman ke email.',
      'notif_test_btn': 'Kirim Notifikasi Uji Coba',
      'notif_test_success': 'Notifikasi uji coba berhasil dikirimkan!',
      // Pusat Bantuan
      'help_faq': 'Pertanyaan Umum (FAQ)',
      'help_contact': 'Hubungi Kami Langsung',
      'help_wa': 'WhatsApp Support',
      'help_email': 'Email Bantuan',
      'help_call': 'Call Center 147',
      'help_ticket_btn': 'Kirim Tiket Keluhan',
      // Tentang
      'about_version': 'Versi Aplikasi',
      'about_desc': 'Sistem Manajemen & Monitoring Armada Kendaraan Dinas PT Telkom Indonesia bekerja sama dengan SV Universitas Pakuan.',
      'about_terms': 'Syarat & Ketentuan',
      'about_privacy': 'Kebijakan Privasi',
      'about_check_update': 'Periksa Pembaruan',
      'about_up_to_date': 'Aplikasi Anda sudah versi terbaru!',
      // Navigasi Bawah
      'nav_dashboard': 'Dashboard',
      'nav_tracking': 'Tracking',
      'nav_history': 'Riwayat',
      'nav_settings': 'Pengaturan',
      // Dashboard
      'dashboard_title': 'Dashboard',
      'dashboard_admin_title': 'Dashboard Admin',
      'dashboard_admin_subtitle': 'Monitoring peminjaman kendaraan operasional',
      'refresh_tooltip': 'Segarkan data',
      'search_dashboard_hint': 'Cari nama mobil, plat, atau peminjam...',
      'summary_total': 'TOTAL BOOKING',
      'summary_pending': 'MENUNGGU ACC',
      'summary_active': 'SEDANG DIPAKAI',
      'summary_completed': 'SELESAI',
      'filter_all': 'Semua',
      'filter_pending': 'Menunggu ACC',
      'filter_active': 'Sedang Dipakai',
      'filter_completed': 'Selesai',
      'booking_data_title': 'Data Peminjaman',
      'booking_list_title': 'Daftar Pengajuan Peminjaman',
      'empty_bookings': 'Belum ada data peminjaman.',
      'data_suffix': 'Data',
      'pending_action_banner': 'Menunggu persetujuan (ACC) dari Anda',
      // Tracking
      'tracking_title': 'Live Tracking Kendaraan',
      'search_tracking_hint': 'Cari mobil, plat, driver, atau tujuan...',
      'map_pool_standby': 'POOL ARMADA • STANDBY',
      'map_live_gps': 'LIVE GPS',
      'map_gps_standby': 'GPS STANDBY',
      'pool_standby_title': 'Pool Armada Siaga (Standby)',
      'pool_standby_desc': 'Semua kendaraan berada di pool. Belum ada perjalanan aktif.',
      'pool_marker_label': 'Pool Telkom Standby',
      'pool_status_ready': 'Siaga',
      'speed_label': 'KECEPATAN',
      'distance_label': 'JARAK TEMPUH',
      'telemetry_title': 'Status Telemetri & Armada',
      'telemetry_desc': 'Monitoring metrik pergerakan armada secara langsung',
      'stat_active_fleet': 'ARMADA TERPAKAI',
      'stat_avg_speed': 'AVG SPEED',
      'stat_max_speed': 'BATAS SPEED',
      'vehicle_list_title': 'Daftar Armada Sedang Dipakai',
      'focus_map_btn': 'Fokuskan di Peta',
      'fullscreen_map_btn': 'Peta Penuh',
      'empty_tracking_title': 'Tidak Ada Armada yang Sedang Dipakai',
      'empty_tracking_desc': 'Semua armada saat ini berstatus standby di pool atau belum ada peminjaman aktif yang disetujui (ACC).',
      'check_dashboard_btn': 'Cek Dashboard',
      'reload_btn': 'Muat Ulang',
      'badge_in_use': 'Sedang Dipakai',
      'borrower_label': 'Peminjam',
      // History
      'history_title': 'Riwayat Peminjaman',
      'search_history_hint': 'Cari nama mobil, plat, atau peminjam...',
      'empty_history': 'Belum ada data riwayat peminjaman.',
      // Status & Actions
      'status_rejected': 'DITOLAK',
      'btn_approve_full': 'ACC / Setujui Peminjaman',
      'btn_reject_booking': 'Tolak',
      'btn_finish_trip': 'Selesaikan Peminjaman',
      'vehicle_in_use_banner': 'KENDARAAN SEDANG DIGUNAKAN',
      'booking_completed_banner': 'PEMINJAMAN SELESAI',
      'booking_rejected_banner': 'PEMINJAMAN TELAH DITOLAK',
      'unit_suffix': 'Unit',
      // Status Armada & Perbaikan
      'fleet_status_title': 'Status Armada & Ketersediaan Unit',
      'fleet_available': 'Tersedia',
      'fleet_in_use': 'Sedang Dipakai',
      'fleet_maintenance': 'Dalam Perbaikan',
      'fleet_ready_desc': 'Armada siaga di pool dan siap dipinjam',
      'fleet_maintenance_desc': 'Armada sedang dalam perbaikan dan tidak dapat dipinjam',
      'fleet_maintenance_status_msg': 'Kendaraan sedang dalam perbaikan',
      'btn_manage_maintenance': 'Kelola Perbaikan & Notifikasi',
      'btn_set_maintenance': 'Setel Perbaikan',
      'btn_finish_maintenance': 'Selesaikan Perbaikan',
      'btn_send_notif': 'Kirim Notifikasi Peminjam',
      'btn_copy_notif': 'Salin Pesan',
      'btn_share_wa': 'Kirim via WhatsApp',
      'dialog_maintenance_title': 'Atur Perbaikan Kendaraan',
    },
    AppLanguage.en: {
      // General Settings
      'settings_title': 'Settings',
      'account': 'ACCOUNT',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'preferences': 'PREFERENCES',
      'notifications': 'Notifications',
      'language': 'Language',
      'help_and_info': 'HELP & INFORMATION',
      'help_center': 'Help Center',
      'about_app': 'About Application',
      'logout': 'Log Out',
      'logout_confirm_title': 'Confirm Logout',
      'logout_confirm_desc': 'Are you sure you want to log out of this admin account?',
      'cancel': 'Cancel',
      'save': 'Save Changes',
      'loading': 'Loading...',
      'success': 'Success',
      'error': 'An Error Occurred',
      // Edit Profile
      'profile_name': 'Full Name',
      'profile_nik': 'Employee ID / NIK',
      'profile_phone': 'Phone / WhatsApp Number',
      'profile_email': 'Admin Email (Read Only)',
      'profile_role': 'System Role',
      'profile_saved': 'Profile updated successfully!',
      // Password
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm New Password',
      'password_min_length': 'At least 6 characters',
      'password_match_error': 'Password confirmation does not match',
      'password_success': 'Password updated successfully!',
      // Notifications
      'notif_title': 'Notification Settings',
      'notif_booking_title': 'New Bookings',
      'notif_booking_desc': 'Get instant alert when an employee submits a new booking request.',
      'notif_geofence_title': 'Geofence Alerts',
      'notif_geofence_desc': 'Emergency alert when a fleet vehicle leaves its designated boundary.',
      'notif_tracking_title': 'Live Tracking',
      'notif_tracking_desc': 'Status updates regarding vehicle movement and location.',
      'notif_sound_title': 'Sound & Vibration',
      'notif_sound_desc': 'Play ringtone for high-priority fleet alerts.',
      'notif_email_title': 'Weekly Summary Email',
      'notif_email_desc': 'Receive weekly summary analytics via email.',
      'notif_test_btn': 'Send Test Notification',
      'notif_test_success': 'Test notification sent successfully!',
      // Help Center
      'help_faq': 'Frequently Asked Questions (FAQ)',
      'help_contact': 'Contact Direct Support',
      'help_wa': 'WhatsApp Support',
      'help_email': 'Email Helpdesk',
      'help_call': 'Call Center 147',
      'help_ticket_btn': 'Submit Support Ticket',
      // About
      'about_version': 'Application Version',
      'about_desc': 'Fleet Management & Monitoring System for PT Telkom Indonesia in collaboration with SV Universitas Pakuan.',
      'about_terms': 'Terms & Conditions',
      'about_privacy': 'Privacy Policy',
      'about_check_update': 'Check for Updates',
      'about_up_to_date': 'Your application is up to date!',
      // Navigation
      'nav_dashboard': 'Dashboard',
      'nav_tracking': 'Tracking',
      'nav_history': 'History',
      'nav_settings': 'Settings',
      // Dashboard
      'dashboard_title': 'Dashboard',
      'dashboard_admin_title': 'Admin Dashboard',
      'dashboard_admin_subtitle': 'Operational vehicle booking monitoring',
      'refresh_tooltip': 'Refresh data',
      'search_dashboard_hint': 'Search car, plate, or borrower...',
      'summary_total': 'TOTAL BOOKINGS',
      'summary_pending': 'PENDING ACC',
      'summary_active': 'IN USE',
      'summary_completed': 'COMPLETED',
      'filter_all': 'All',
      'filter_pending': 'Pending ACC',
      'filter_active': 'In Use',
      'filter_completed': 'Completed',
      'booking_data_title': 'Booking Data',
      'booking_list_title': 'Booking Request List',
      'empty_bookings': 'No booking data yet.',
      'data_suffix': 'Records',
      'pending_action_banner': 'Waiting for your approval (ACC)',
      // Tracking
      'tracking_title': 'Live Vehicle Tracking',
      'search_tracking_hint': 'Search car, plate, driver, or destination...',
      'map_pool_standby': 'FLEET POOL • STANDBY',
      'map_live_gps': 'LIVE GPS',
      'map_gps_standby': 'GPS STANDBY',
      'pool_standby_title': 'Fleet Pool Standby',
      'pool_standby_desc': 'All fleet vehicles are currently at the pool. No active trips.',
      'pool_marker_label': 'Telkom Pool Standby',
      'pool_status_ready': 'Standby',
      'speed_label': 'SPEED',
      'distance_label': 'DISTANCE',
      'telemetry_title': 'Telemetry & Fleet Status',
      'telemetry_desc': 'Real-time fleet telemetry and movement metrics',
      'stat_active_fleet': 'FLEET IN USE',
      'stat_avg_speed': 'AVG SPEED',
      'stat_max_speed': 'SPEED LIMIT',
      'vehicle_list_title': 'Fleet Currently In Use',
      'focus_map_btn': 'Center on Map',
      'fullscreen_map_btn': 'Fullscreen Map',
      'empty_tracking_title': 'No Fleet Currently in Use',
      'empty_tracking_desc': 'All fleet vehicles are on standby at the pool or no active bookings approved.',
      'check_dashboard_btn': 'Check Dashboard',
      'reload_btn': 'Reload',
      'badge_in_use': 'In Use',
      'borrower_label': 'Borrower',
      // History
      'history_title': 'Booking History',
      'search_history_hint': 'Search car name, plate, or borrower...',
      'empty_history': 'No booking history data yet.',
      // Status & Actions
      'status_rejected': 'REJECTED',
      'btn_approve_full': 'Approve Booking (ACC)',
      'btn_reject_booking': 'Reject',
      'btn_finish_trip': 'Complete Booking',
      'vehicle_in_use_banner': 'VEHICLE CURRENTLY IN USE',
      'booking_completed_banner': 'BOOKING COMPLETED',
      'booking_rejected_banner': 'BOOKING REJECTED',
      'unit_suffix': 'Units',
      // Fleet Status & Maintenance
      'fleet_status_title': 'Fleet Status & Availability',
      'fleet_available': 'Available',
      'fleet_in_use': 'In Use',
      'fleet_maintenance': 'Maintenance',
      'fleet_ready_desc': 'Fleet ready at pool and available for booking',
      'fleet_maintenance_desc': 'Vehicle is undergoing maintenance and cannot be booked',
      'fleet_maintenance_status_msg': 'Vehicle is currently under maintenance',
      'btn_manage_maintenance': 'Manage Maintenance & Notify',
      'btn_set_maintenance': 'Set Maintenance',
      'btn_finish_maintenance': 'Complete Maintenance',
      'btn_send_notif': 'Notify Borrowers',
      'btn_copy_notif': 'Copy Message',
      'btn_share_wa': 'Send via WhatsApp',
      'dialog_maintenance_title': 'Manage Vehicle Maintenance',
    },
    AppLanguage.su: {
      // Setelan Umum
      'settings_title': 'Setélan',
      'account': 'AKUN',
      'edit_profile': 'Ngarobih Profil',
      'change_password': 'Robih Kecap Sandi',
      'preferences': 'PILIHAN',
      'notifications': 'Bewara',
      'language': 'Basa',
      'help_and_info': 'PITULUNG & INFORMASI',
      'help_center': 'Puseur Pitulung',
      'about_app': 'Ngeunaan Aplikasi',
      'logout': 'Kaluar tina Akun',
      'logout_confirm_title': 'Konfirmasi Kaluar',
      'logout_confirm_desc': 'Naha anjeun yakin hoyong kaluar tina akun ieu?',
      'cancel': 'Bolay',
      'save': 'Simpen Parobahan',
      'loading': 'Ngamuat...',
      'success': 'Kacatet / Hasil',
      'error': 'Aya Kasalahan',
      // Edit Profil
      'profile_name': 'Nami Lengkep',
      'profile_nik': 'NIK / Nomer Karyawan',
      'profile_phone': 'Nomer Telepon / WhatsApp',
      'profile_email': 'Email Akun Admin (Henteu tiasa dirobih)',
      'profile_role': 'Peran Sistem',
      'profile_saved': 'Profil parantos hasil dirobih!',
      // Kata Sandi
      'current_password': 'Kecap Sandi Heubeul',
      'new_password': 'Kecap Sandi Anyar',
      'confirm_password': 'Pastikeun Kecap Sandi',
      'password_min_length': 'Sahenteuna 6 karakter',
      'password_match_error': 'Kecap sandi teu sami',
      'password_success': 'Kecap sandi parantos hasil dirobih!',
      // Notifikasi
      'notif_title': 'Setélan Bewara',
      'notif_booking_title': 'Nambut Anyar',
      'notif_booking_desc': 'Kengingkeun béwara langsung nalika aya anu nambut kandaraan.',
      'notif_geofence_title': 'Peringatan Geofence',
      'notif_geofence_desc': 'Bewara darurat upami kandaraan kaluar tina wilayah aman.',
      'notif_tracking_title': 'Live Tracking',
      'notif_tracking_desc': 'Pembaruan lokasi sareng kaayaan kandaraan dinas.',
      'notif_sound_title': 'Sora & Geter',
      'notif_sound_desc': 'Hurungkeun sora pikeun béwara anu penting.',
      'notif_email_title': 'Laporan Mingguan Email',
      'notif_email_desc': 'Kintunkeun rekap data nambut kana email.',
      'notif_test_btn': 'Uji Coba Bewara',
      'notif_test_success': 'Bewara uji coba parantos hasil dikintun!',
      // Pusat Bantuan
      'help_faq': 'Patarosan Umum (FAQ)',
      'help_contact': 'Hubungi Admin Langsung',
      'help_wa': 'WhatsApp Support',
      'help_email': 'Email Bantuan',
      'help_call': 'Call Center 147',
      'help_ticket_btn': 'Kintun Tiket Pitulung',
      // Tentang
      'about_version': 'Vérsi Aplikasi',
      'about_desc': 'Sistem Monitoring Armada Kandaraan Dinas PT Telkom Indonesia gawé bareng sareng SV Universitas Pakuan.',
      'about_terms': 'Sarat & Katangtuan',
      'about_privacy': 'Kawijakan Privasi',
      'about_check_update': 'Pariksa Pembaruan',
      'about_up_to_date': 'Aplikasi anjeun parantos vérsi panganyarna!',
      // Navigasi
      'nav_dashboard': 'Dasbor',
      'nav_tracking': 'Lacak',
      'nav_history': 'Jujutan',
      'nav_settings': 'Setélan',
      // Dashboard
      'dashboard_title': 'Dasbor',
      'dashboard_admin_title': 'Dasbor Admin',
      'dashboard_admin_subtitle': 'Monitoring nambut kandaraan operasional',
      'refresh_tooltip': 'Segarkeun data',
      'search_dashboard_hint': 'Milari mobil, plat, atanapi nu nambut...',
      'summary_total': 'TOTAL NAMBUT',
      'summary_pending': 'NGAREOS ACC',
      'summary_active': 'NUJU DIPAKÉ',
      'summary_completed': 'PARANTOS RÉNGSÉ',
      'filter_all': 'Sadayana',
      'filter_pending': 'Ngareos ACC',
      'filter_active': 'Nuju Dipaké',
      'filter_completed': 'Réngsé',
      'booking_data_title': 'Data Nambut Kandaraan',
      'booking_list_title': 'Daptar Pamenta Nambut Kandaraan',
      'empty_bookings': 'Teu acan aya data nambut.',
      'data_suffix': 'Data',
      'pending_action_banner': 'Ngantosan kasatujuan (ACC) ti Anjeun',
      // Tracking
      'tracking_title': 'Lacak Kandaraan Langsung',
      'search_tracking_hint': 'Milari mobil, plat, supir, atanapi tujuan...',
      'map_pool_standby': 'POOL ARMADA • SIAGA',
      'map_live_gps': 'GPS LANGSUNG',
      'map_gps_standby': 'GPS SIAGA',
      'pool_standby_title': 'Pool Armada Siaga (Standby)',
      'pool_standby_desc': 'Sadaya kandaraan nuju aya di pool. Teu acan aya perjalanan aktif.',
      'pool_marker_label': 'Pool Telkom Siaga',
      'pool_status_ready': 'Siaga',
      'speed_label': 'KAGANCANGAN',
      'distance_label': 'JARAK TEMPUH',
      'telemetry_title': 'Status Telemetri & Armada',
      'telemetry_desc': 'Monitoring obahna armada sacara langsung',
      'stat_active_fleet': 'ARMADA KANGGÉ',
      'stat_avg_speed': 'GANCANG RATA',
      'stat_max_speed': 'BATAS GANCANG',
      'vehicle_list_title': 'Daptar Armada Nuju Dipaké',
      'focus_map_btn': 'Tingal dina Peta',
      'fullscreen_map_btn': 'Peta Pinuh',
      'empty_tracking_title': 'Teu Aya Armada Anu Nuju Dipaké',
      'empty_tracking_desc': 'Sadaya armada nuju standby di pool atanapi teu acan aya anu disatujuan (ACC).',
      'check_dashboard_btn': 'Tingal Dasbor',
      'reload_btn': 'Muat Deui',
      'badge_in_use': 'Nuju Dipaké',
      'borrower_label': 'Nu Nambut',
      // History
      'history_title': 'Jujutan Nambut Kandaraan',
      'search_history_hint': 'Milari nami mobil, plat, atanapi nu nambut...',
      'empty_history': 'Teu acan aya data jujutan nambut.',
      // Status & Actions
      'status_rejected': 'DITOLAK',
      'btn_approve_full': 'ACC / Satujuan Nambut',
      'btn_reject_booking': 'Tolak',
      'btn_finish_trip': 'Rengsekeun Nambut',
      'vehicle_in_use_banner': 'KANDARAAN NUJU DIPAKÉ',
      'booking_completed_banner': 'NAMBUT PARANTOS RÉNGSÉ',
      'booking_rejected_banner': 'NAMBUT PARANTOS DITOLAK',
      'unit_suffix': 'Unit',
      // Status Armada & Perbaikan
      'fleet_status_title': 'Status Armada & Kasadiaan Unit',
      'fleet_available': 'Sayaga',
      'fleet_in_use': 'Nuju Dipaké',
      'fleet_maintenance': 'Nuju Dilereskeun',
      'fleet_ready_desc': 'Armada sayaga di pool siap ditambut',
      'fleet_maintenance_desc': 'Kandaraan nuju dilereskeun, teu tiasa ditambut',
      'fleet_maintenance_status_msg': 'Kandaraan nuju dilereskeun',
      'btn_manage_maintenance': 'Atur Parawatan & Bewara',
      'btn_set_maintenance': 'Setél Dilereskeun',
      'btn_finish_maintenance': 'Rengse Dilereskeun',
      'btn_send_notif': 'Kintun Bewara ka Nu Nambut',
      'btn_copy_notif': 'Salin Pesen',
      'btn_share_wa': 'Kintun via WhatsApp',
      'dialog_maintenance_title': 'Atur Parawatan Kandaraan',
    },
    AppLanguage.jv: {
      // Setelan Umum
      'settings_title': 'Setelan',
      'account': 'AKUN',
      'edit_profile': 'Ganti Profil',
      'change_password': 'Ganti Sandi',
      'preferences': 'PREFERENSI',
      'notifications': 'Notifikasi',
      'language': 'Basa',
      'help_and_info': 'PITULUNGAN & INFORMASI',
      'help_center': 'Pusat Pitulungan',
      'about_app': 'Babagan Aplikasi',
      'logout': 'Metu saka Akun',
      'logout_confirm_title': 'Konfirmasi Metu',
      'logout_confirm_desc': 'Punapa panjenengan yakin badhe medal saking akun admin punika?',
      'cancel': 'Batal',
      'save': 'Simpen Owah-owahan',
      'loading': 'Ngamot...',
      'success': 'Kasil',
      'error': 'Wonten Kalepatan',
      // Edit Profil
      'profile_name': 'Jeneng Jangkep',
      'profile_nik': 'NIK / Nomer Karyawan',
      'profile_phone': 'Nomer Telepon / WhatsApp',
      'profile_email': 'Email Akun Admin (Mboten saged dipun-owahi)',
      'profile_role': 'Peran Sistem',
      'profile_saved': 'Profil kasil dipun-anyari!',
      // Kata Sandi
      'current_password': 'Sandi Lawas',
      'new_password': 'Sandi Anyar',
      'confirm_password': 'Konfirmasi Sandi Anyar',
      'password_min_length': 'Paling sithik 6 aksara',
      'password_match_error': 'Sandi mboten padha',
      'password_success': 'Sandi kasil dipun-anyari!',
      // Notifikasi
      'notif_title': 'Setelan Notifikasi',
      'notif_booking_title': 'Nyilih Anyar',
      'notif_booking_desc': 'Pikantuk kabar nalika wonten pengajuan nyilih armada anyar.',
      'notif_geofence_title': 'Peringatan Geofence',
      'notif_geofence_desc': 'Peringatan penting menawi kendaraan medal saking wates wilayah.',
      'notif_tracking_title': 'Live Tracking',
      'notif_tracking_desc': 'Kabar posisi lan status mobil dinas sacara langsung.',
      'notif_sound_title': 'Swara & Geter',
      'notif_sound_desc': 'Munyikaken swara kagem kabar ingkang wigati.',
      'notif_email_title': 'Laporan Mingguan Email',
      'notif_email_desc': 'Kintun rekap lapuran armada dhateng email.',
      'notif_test_btn': 'Cobi Kirim Notifikasi',
      'notif_test_success': 'Notifikasi uji coba kasil dipunkintun!',
      // Pusat Bantuan
      'help_faq': 'Pitakon Umum (FAQ)',
      'help_contact': 'Hubungi Langsung',
      'help_wa': 'WhatsApp Support',
      'help_email': 'Email Pitulungan',
      'help_call': 'Call Center 147',
      'help_ticket_btn': 'Kintun Tiket Pitulungan',
      // Tentang
      'about_version': 'Versi Aplikasi',
      'about_desc': 'Sistem Monitoring Armada Kendaraan Dinas PT Telkom Indonesia sesarengan kalian SV Universitas Pakuan.',
      'about_terms': 'Syarat & Katemtuan',
      'about_privacy': 'Kawicaksanan Privasi',
      'about_check_update': 'Priksa Pembaruan',
      'about_up_to_date': 'Aplikasi panjenengan sampun versi ingkang paling anyar!',
      // Navigasi
      'nav_dashboard': 'Dasbor',
      'nav_tracking': 'Lacak',
      'nav_history': 'Riwayat',
      'nav_settings': 'Setelan',
      // Dashboard
      'dashboard_title': 'Dasbor',
      'dashboard_admin_title': 'Dasbor Admin',
      'dashboard_admin_subtitle': 'Monitoring nyilih kendaraan operasional',
      'refresh_tooltip': 'Anyari data',
      'search_dashboard_hint': 'Golek mobil, plat, utawa sing nyilih...',
      'summary_total': 'TOTAL NYILIH',
      'summary_pending': 'NUNGGU ACC',
      'summary_active': 'LAGI DIENGGO',
      'summary_completed': 'RAMPUNG',
      'filter_all': 'Kabeh',
      'filter_pending': 'Nunggu ACC',
      'filter_active': 'Lagi Dienggo',
      'filter_completed': 'Rampung',
      'booking_data_title': 'Data Nyilih Kendaraan',
      'booking_list_title': 'Dhaptar Panyuwunan Nyilih',
      'empty_bookings': 'Durung ana data nyilih.',
      'data_suffix': 'Data',
      'pending_action_banner': 'Ngentosi persetujuan (ACC) saking Panjenengan',
      // Tracking
      'tracking_title': 'Lacak Kendaraan Langsung',
      'search_tracking_hint': 'Golek mobil, plat, supir, utawa tujuwan...',
      'map_pool_standby': 'POOL ARMADA • SIAGA',
      'map_live_gps': 'GPS LANGSUNG',
      'map_gps_standby': 'GPS SIAGA',
      'pool_standby_title': 'Pool Armada Siaga (Standby)',
      'pool_standby_desc': 'Kabeh kendaraan lagi ana ing pool. Durung ana lelampahan aktif.',
      'pool_marker_label': 'Pool Telkom Siaga',
      'pool_status_ready': 'Siaga',
      'speed_label': 'KACEPETAN',
      'distance_label': 'JARAK TEMPUH',
      'telemetry_title': 'Status Telemetri & Armada',
      'telemetry_desc': 'Monitoring obahe armada kanthi langsung',
      'stat_active_fleet': 'ARMADA DIENGGO',
      'stat_avg_speed': 'KACEPETAN RATA',
      'stat_max_speed': 'WATES CEPET',
      'vehicle_list_title': 'Dhaptar Armada Lagi Dienggo',
      'focus_map_btn': 'Pusengake ing Peta',
      'fullscreen_map_btn': 'Peta Kebak',
      'empty_tracking_title': 'Ora Ana Armada Sing Lagi Dienggo',
      'empty_tracking_desc': 'Kabeh armada lagi standby ing pool utawa durung ana nyilih aktif sing disetujoni (ACC).',
      'check_dashboard_btn': 'Priksa Dasbor',
      'reload_btn': 'Amot Maneh',
      'badge_in_use': 'Lagi Dienggo',
      'borrower_label': 'Sing Nyilih',
      // History
      'history_title': 'Riwayat Nyilih Kendaraan',
      'search_history_hint': 'Golek jeneng mobil, plat, utawa sing nyilih...',
      'empty_history': 'Durung ana data riwayat nyilih.',
      // Status & Actions
      'status_rejected': 'DITOLAK',
      'btn_approve_full': 'ACC / Setujoni Nyilih',
      'btn_reject_booking': 'Tolak',
      'btn_finish_trip': 'Rampungake Nyilih',
      'vehicle_in_use_banner': 'KENDARAAN LAGI DIENGGO',
      'booking_completed_banner': 'NYILIH SAMPUN RAMPUNG',
      'booking_rejected_banner': 'NYILIH SAMPUN DIPUNTOLAK',
      'unit_suffix': 'Unit',
      // Status Armada & Perbaikan
      'fleet_status_title': 'Status Armada & Kasamektan Unit',
      'fleet_available': 'Sumadya',
      'fleet_in_use': 'Lagi Dienggo',
      'fleet_maintenance': 'Lagi Didandani',
      'fleet_ready_desc': 'Armada siaga ing pool lan sumadya disilih',
      'fleet_maintenance_desc': 'Kendaraan lagi didandani lan ora bisa disilih',
      'fleet_maintenance_status_msg': 'Kendaraan lagi didandani',
      'btn_manage_maintenance': 'Atur Dandanan & Notifikasi',
      'btn_set_maintenance': 'Setel Didandani',
      'btn_finish_maintenance': 'Rampung Didandani',
      'btn_send_notif': 'Kirim Notifikasi Panyilih',
      'btn_copy_notif': 'Salin Pesen',
      'btn_share_wa': 'Kirim via WhatsApp',
      'dialog_maintenance_title': 'Atur Dandanan Kendaraan',
    },
  };

  String t(String key) {
    final langMap = _translations[currentLanguage];
    if (langMap != null && langMap.containsKey(key)) {
      return langMap[key]!;
    }
    // Fallback to Indonesian if key not found
    return _translations[AppLanguage.id]?[key] ?? key;
  }
}
